### ISSUE TITLE
Database mods

### ISSUE THREAD

**Issue by brnorris03** [HPCL/ideas-uo#10]
Database models.py changes:
- [x] 1. The "fork of" and "child of" values in the projects table should be
- [x] 2.  optional. (Project module)
- [x] 2. The closed_at value should be allowed to be null (for open issues) in Issue
- [x] 3. The due_on and description fields in Milestone
- [x] 4. Author.username -- allow null? There were some cases where that was true, e.g. 
       `[DEBUG]: 2021-09-16 18:20:24,269 - Nek5000: Inserting new comment for issue 5430 from author 3790`

Update django_ideas models.py to reflect the above.

**Comment by brnorris03** [comment]
@jprideaux can you please check if above commit is correct, then update the db and restart the server?

**Comment by brnorris03** [comment]
Another Milestone.description fix included in 16462ab

**Comment by jprideaux** [comment]
Changes to the models looks good. I'll create the db migrations and test it out.  Not sure about the author change, though.  If the username is null, is there any guarantee that the other fields will have values?  I worry about junk data where we have lots of unknown users, or worse every null username gets grouped together as one.

**Comment by brnorris03** [comment]
I don't know, maybe we can have a special value for those author entries? I
think there should be very few based on the number of errors I got.

**Comment by jprideaux** [comment]
Ok, I’ll make the change then, and then if there’s a lot we can deal with it then.  I agree that it probably won’t be many.

-Jason
