### ISSUE TITLE
TypeError while retrieving commit data through GitCommand

### ISSUE THREAD

**Issue by ndemeyembosco** [HPCL/ideas-uo#4]
get "_a bytes-like object is required, not 'str'_ " when getRepoCommitData is called with spack

`comms = commander.getRepoCommitData('/content/ideas-uo/code/tmp/spack')`

![image](https://user-images.githubusercontent.com/24593451/108917986-77a20700-75e5-11eb-92fb-513c4f369b6e.png)

**Comment by CarterPerkins** [comment]
Fixed.
